### PR TITLE
Added Palworld Support and Tested on Steam

### PR DESCRIPTION
**Pull request by Doct-Holiday**
Steam Save File location is here: C:\Users\YOUR_NAME\AppData\Local\Pal\Saved\SaveGames

Replace and rename each file with the ones generated by XGP

### CODE REVIEW

**Comment by Z1ni** [comment]
Thanks!

**Comment by maxfruity** [comment]
What does replacing and renaming each file mean? There are some folders I can go farther into, Do I? Sorry if these are stupid questions!

**Comment by Doct-Holiday** [comment]
@maxfruity the files generated by XGP have a bunch of characters

Example: ACF08C2F486764723D034393783D3B71-Players-00000000000000000000000000000001.sav

When you navigate to the steam player folder you really only see "00000000000000000000000000000001.sav"

So rename the XGP file to match the steam one and repeat this process for all other files

**Comment by Z1ni** [comment]
I made a small change to the Palworld save handling, it now creates the directory structure, so there should be no need to rename files. Check out https://github.com/Z1ni/XGP-save-extractor/releases/tag/release-2024-01-21.

**Pull request merged**
